# Generated by Django 4.1.5 on 2023-03-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reminder_day',
            field=models.IntegerField(default=0),
        ),
    ]
