version: '3.8'

services:
  analytics_app_gateway:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/src
    ports:
      - 8000:8000
    env_file:
      - .env
