version: '3.8'

services:
  prop_swift_gateway:
    env_file:
      - .env
    build: .
    image: prop_swift_service_image:latest
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        max_failure_ratio: 0
        delay: 3s
        failure_action: rollback
      restart_policy:
        max_attempts: 3
        condition: on-failure
      placement:
        constraints: [node.role == manager]
    volumes:
      - .:/src
    networks:
        - prop_network
networks:
    prop_network:
      external: true

