# Generated by Django 4.1.5 on 2023-01-17 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyimages',
            old_name='image',
            new_name='file',
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_images_uploader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='property.property'),
        ),
    ]
