# Generated by Django 4.1.5 on 2023-01-26 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_rename_end_date_propertyrent_date_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyexpense',
            name='receipt',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='propertyimages',
            name='expense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_images', to='property.propertyexpense'),
        ),
    ]
