# Generated by Django 4.1.5 on 2023-01-26 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_propertyexpense_receipt_propertyimages_expense'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyexpense',
            options={'ordering': ['-created_at']},
        ),
    ]
