# Generated by Django 4.1.5 on 2023-01-26 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_propertyexpense_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimages',
            name='rent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent_images', to='property.propertyrent'),
        ),
        migrations.AddField(
            model_name='propertyrent',
            name='receipt',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
