# Generated by Django 4.1.5 on 2023-01-26 07:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0006_propertyimages_rent_propertyrent_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='managers',
            field=models.ManyToManyField(related_name='property_managers', to=settings.AUTH_USER_MODEL),
        ),
    ]
