# Generated by Django 4.1.5 on 2023-03-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_otherreceipts_propertyimages_other_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='date_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
